name: Publish Package

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: write

jobs:
  publish-npm:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm to latest
        run: npm i -g npm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Generate changelog
        run: npx changelogithub --no-group
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish package to npm
        run: pnpm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
          NODE_OPTIONS: --max-old-space-size=6144
